import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaWhatsapp } from "react-icons/fa";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Arrham Groups",

  description: "Generated by create next app",
  icons: {
    icon: "/logo.png"
  }
};

export default function RootLayout({ children }) {
  const phone = "97335372929";
  const message = "Hello, I came from your website and want to know more.";
  const url = `https://wa.me/${phone}?text=${encodeURIComponent(message)}`;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="group z-50 fixed bottom-4 right-10 flex items-center justify-center 
                 w-16 h-16 rounded-full bg-transparent shadow-lg cursor-pointer
                 transition-all duration-500 ease-out
                 hover:bg-gradient-to-br hover:from-green-400 hover:to-green-500 
                 hover:scale-110 hover:shadow-[0_0_35px_12px_rgba(37,211,102,0.55)]"
        >
          <FaWhatsapp
            size={36}
            className=" text-green-500 transition-colors duration-300 group-hover:text-white"
          />
        </a>

        <Footer />
      </body>
    </html>
  );
}
